CHECKLIST_CMD = ('add', 'finish', 'remove', 'clear', 'checklist')
ASSIGNMENT_CMD = ('save', 'assignments', 'delete')
CALENDAR_CMD = ('calendar', 'today', 'month')
NOTES_CMD = ('upload', 'notes', 'pull', 'delete', 'view')
COURSE_CMD = ('schedule', 'courses', 'drop')
POMODORO_CMD = ('timer', 'restart', 'pause')