CHECKLIST_CMD = ('add', 'finish', 'remove', 'clear', 'checklist')
ASSIGNMENT_CMD = ()
CALENDAR_CMD = ()
NOTES_CMD = ('upload', 'notes', 'pull', 'delete', 'view')
COURSE_CMD = ()
POMODORO_CMD = ('timer', 'restart', 'pause')